## 视频配置
video-config:
  ##Server地址前缀
  server-path: http:\\192.168.0.1:6001\ # your server-path
  ##视频保存路径
  video-save-path: videos #your target folder name
  ##视频封面保存路径
  video-cover-save-path: covers #your target folder name
  ##配置封面截取第几帧
  frame-num: 1
  ##feed流至多返回多少条视频
  feed-video-max-num: 15

##配置mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kdoushen?characterEncoding=utf-8&serverTimezone=UTC #your url
    username: admin #your username
    password: admin #your password
    driver-class-name: com.mysql.cj.jdbc.Driver
  transaction:
    default-timeout: 3
  ##配置redis
  redis:
    host: localhost
    port: 6379

  activemq:
    broker-url: tcp://192.168.0.1:61616 #your url
    user: admin #your username
    password: admin #your password
    pool:
      enabled: true
      max-connections: 10


server:
  port: 6001 #your port

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl