// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite_action.proto

package com.example.kdoushen.douyin.bean.protobuf.extra.first;

public final class FavoriteAction {
  private FavoriteAction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface douyin_favorite_action_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:douyin.extra.first.douyin_favorite_action_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>required int64 user_id = 1;</code>
     * @return Whether the userId field is set.
     */
    boolean hasUserId();
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>required int64 user_id = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return Whether the token field is set.
     */
    boolean hasToken();
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *视频id
     * </pre>
     *
     * <code>required int64 video_id = 3;</code>
     * @return Whether the videoId field is set.
     */
    boolean hasVideoId();
    /**
     * <pre>
     *视频id
     * </pre>
     *
     * <code>required int64 video_id = 3;</code>
     * @return The videoId.
     */
    long getVideoId();

    /**
     * <pre>
     *1-点赞 0-取消
     * </pre>
     *
     * <code>required int32 actionType = 4;</code>
     * @return Whether the actionType field is set.
     */
    boolean hasActionType();
    /**
     * <pre>
     *1-点赞 0-取消
     * </pre>
     *
     * <code>required int32 actionType = 4;</code>
     * @return The actionType.
     */
    int getActionType();
  }
  /**
   * Protobuf type {@code douyin.extra.first.douyin_favorite_action_request}
   */
  public static final class douyin_favorite_action_request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:douyin.extra.first.douyin_favorite_action_request)
      douyin_favorite_action_requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use douyin_favorite_action_request.newBuilder() to construct.
    private douyin_favorite_action_request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private douyin_favorite_action_request() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new douyin_favorite_action_request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private douyin_favorite_action_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              token_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              videoId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              actionType_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FavoriteAction.douyin_favorite_action_request.class, FavoriteAction.douyin_favorite_action_request.Builder.class);
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>required int64 user_id = 1;</code>
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>required int64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return Whether the token field is set.
     */
    @java.lang.Override
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIDEO_ID_FIELD_NUMBER = 3;
    private long videoId_;
    /**
     * <pre>
     *视频id
     * </pre>
     *
     * <code>required int64 video_id = 3;</code>
     * @return Whether the videoId field is set.
     */
    @java.lang.Override
    public boolean hasVideoId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *视频id
     * </pre>
     *
     * <code>required int64 video_id = 3;</code>
     * @return The videoId.
     */
    @java.lang.Override
    public long getVideoId() {
      return videoId_;
    }

    public static final int ACTIONTYPE_FIELD_NUMBER = 4;
    private int actionType_;
    /**
     * <pre>
     *1-点赞 0-取消
     * </pre>
     *
     * <code>required int32 actionType = 4;</code>
     * @return Whether the actionType field is set.
     */
    @java.lang.Override
    public boolean hasActionType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *1-点赞 0-取消
     * </pre>
     *
     * <code>required int32 actionType = 4;</code>
     * @return The actionType.
     */
    @java.lang.Override
    public int getActionType() {
      return actionType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVideoId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, videoId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, actionType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, videoId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, actionType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FavoriteAction.douyin_favorite_action_request)) {
        return super.equals(obj);
      }
      FavoriteAction.douyin_favorite_action_request other = (FavoriteAction.douyin_favorite_action_request) obj;

      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (getUserId()
            != other.getUserId()) return false;
      }
      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (hasVideoId() != other.hasVideoId()) return false;
      if (hasVideoId()) {
        if (getVideoId()
            != other.getVideoId()) return false;
      }
      if (hasActionType() != other.hasActionType()) return false;
      if (hasActionType()) {
        if (getActionType()
            != other.getActionType()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserId()) {
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
      }
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      if (hasVideoId()) {
        hash = (37 * hash) + VIDEO_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVideoId());
      }
      if (hasActionType()) {
        hash = (37 * hash) + ACTIONTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getActionType();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FavoriteAction.douyin_favorite_action_request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FavoriteAction.douyin_favorite_action_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FavoriteAction.douyin_favorite_action_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FavoriteAction.douyin_favorite_action_request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code douyin.extra.first.douyin_favorite_action_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:douyin.extra.first.douyin_favorite_action_request)
        FavoriteAction.douyin_favorite_action_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FavoriteAction.douyin_favorite_action_request.class, FavoriteAction.douyin_favorite_action_request.Builder.class);
      }

      // Construct using douyin.extra.first.FavoriteAction.douyin_favorite_action_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        videoId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        actionType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_request_descriptor;
      }

      @java.lang.Override
      public FavoriteAction.douyin_favorite_action_request getDefaultInstanceForType() {
        return FavoriteAction.douyin_favorite_action_request.getDefaultInstance();
      }

      @java.lang.Override
      public FavoriteAction.douyin_favorite_action_request build() {
        FavoriteAction.douyin_favorite_action_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FavoriteAction.douyin_favorite_action_request buildPartial() {
        FavoriteAction.douyin_favorite_action_request result = new FavoriteAction.douyin_favorite_action_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.videoId_ = videoId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.actionType_ = actionType_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FavoriteAction.douyin_favorite_action_request) {
          return mergeFrom((FavoriteAction.douyin_favorite_action_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FavoriteAction.douyin_favorite_action_request other) {
        if (other == FavoriteAction.douyin_favorite_action_request.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000002;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasVideoId()) {
          setVideoId(other.getVideoId());
        }
        if (other.hasActionType()) {
          setActionType(other.getActionType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUserId()) {
          return false;
        }
        if (!hasToken()) {
          return false;
        }
        if (!hasVideoId()) {
          return false;
        }
        if (!hasActionType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FavoriteAction.douyin_favorite_action_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FavoriteAction.douyin_favorite_action_request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>required int64 user_id = 1;</code>
       * @return Whether the userId field is set.
       */
      @java.lang.Override
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>required int64 user_id = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>required int64 user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>required int64 user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @return Whether the token field is set.
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }

      private long videoId_ ;
      /**
       * <pre>
       *视频id
       * </pre>
       *
       * <code>required int64 video_id = 3;</code>
       * @return Whether the videoId field is set.
       */
      @java.lang.Override
      public boolean hasVideoId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *视频id
       * </pre>
       *
       * <code>required int64 video_id = 3;</code>
       * @return The videoId.
       */
      @java.lang.Override
      public long getVideoId() {
        return videoId_;
      }
      /**
       * <pre>
       *视频id
       * </pre>
       *
       * <code>required int64 video_id = 3;</code>
       * @param value The videoId to set.
       * @return This builder for chaining.
       */
      public Builder setVideoId(long value) {
        bitField0_ |= 0x00000004;
        videoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *视频id
       * </pre>
       *
       * <code>required int64 video_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        videoId_ = 0L;
        onChanged();
        return this;
      }

      private int actionType_ ;
      /**
       * <pre>
       *1-点赞 0-取消
       * </pre>
       *
       * <code>required int32 actionType = 4;</code>
       * @return Whether the actionType field is set.
       */
      @java.lang.Override
      public boolean hasActionType() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *1-点赞 0-取消
       * </pre>
       *
       * <code>required int32 actionType = 4;</code>
       * @return The actionType.
       */
      @java.lang.Override
      public int getActionType() {
        return actionType_;
      }
      /**
       * <pre>
       *1-点赞 0-取消
       * </pre>
       *
       * <code>required int32 actionType = 4;</code>
       * @param value The actionType to set.
       * @return This builder for chaining.
       */
      public Builder setActionType(int value) {
        bitField0_ |= 0x00000008;
        actionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1-点赞 0-取消
       * </pre>
       *
       * <code>required int32 actionType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearActionType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        actionType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:douyin.extra.first.douyin_favorite_action_request)
    }

    // @@protoc_insertion_point(class_scope:douyin.extra.first.douyin_favorite_action_request)
    private static final FavoriteAction.douyin_favorite_action_request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FavoriteAction.douyin_favorite_action_request();
    }

    public static FavoriteAction.douyin_favorite_action_request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<douyin_favorite_action_request>
        PARSER = new com.google.protobuf.AbstractParser<douyin_favorite_action_request>() {
      @java.lang.Override
      public douyin_favorite_action_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new douyin_favorite_action_request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<douyin_favorite_action_request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<douyin_favorite_action_request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FavoriteAction.douyin_favorite_action_request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface douyin_favorite_action_responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:douyin.extra.first.douyin_favorite_action_response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *状态码，0-成功，其他-失败
     * </pre>
     *
     * <code>required int32 status_code = 1;</code>
     * @return Whether the statusCode field is set.
     */
    boolean hasStatusCode();
    /**
     * <pre>
     *状态码，0-成功，其他-失败
     * </pre>
     *
     * <code>required int32 status_code = 1;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return Whether the statusMsg field is set.
     */
    boolean hasStatusMsg();
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return The statusMsg.
     */
    java.lang.String getStatusMsg();
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return The bytes for statusMsg.
     */
    com.google.protobuf.ByteString
        getStatusMsgBytes();
  }
  /**
   * Protobuf type {@code douyin.extra.first.douyin_favorite_action_response}
   */
  public static final class douyin_favorite_action_response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:douyin.extra.first.douyin_favorite_action_response)
      douyin_favorite_action_responseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use douyin_favorite_action_response.newBuilder() to construct.
    private douyin_favorite_action_response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private douyin_favorite_action_response() {
      statusMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new douyin_favorite_action_response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private douyin_favorite_action_response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              statusCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              statusMsg_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FavoriteAction.douyin_favorite_action_response.class, FavoriteAction.douyin_favorite_action_response.Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_CODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <pre>
     *状态码，0-成功，其他-失败
     * </pre>
     *
     * <code>required int32 status_code = 1;</code>
     * @return Whether the statusCode field is set.
     */
    @java.lang.Override
    public boolean hasStatusCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *状态码，0-成功，其他-失败
     * </pre>
     *
     * <code>required int32 status_code = 1;</code>
     * @return The statusCode.
     */
    @java.lang.Override
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int STATUS_MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object statusMsg_;
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return Whether the statusMsg field is set.
     */
    @java.lang.Override
    public boolean hasStatusMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return The statusMsg.
     */
    @java.lang.Override
    public java.lang.String getStatusMsg() {
      java.lang.Object ref = statusMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          statusMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return The bytes for statusMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusMsgBytes() {
      java.lang.Object ref = statusMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatusCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, statusCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, statusMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, statusCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, statusMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FavoriteAction.douyin_favorite_action_response)) {
        return super.equals(obj);
      }
      FavoriteAction.douyin_favorite_action_response other = (FavoriteAction.douyin_favorite_action_response) obj;

      if (hasStatusCode() != other.hasStatusCode()) return false;
      if (hasStatusCode()) {
        if (getStatusCode()
            != other.getStatusCode()) return false;
      }
      if (hasStatusMsg() != other.hasStatusMsg()) return false;
      if (hasStatusMsg()) {
        if (!getStatusMsg()
            .equals(other.getStatusMsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatusCode()) {
        hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getStatusCode();
      }
      if (hasStatusMsg()) {
        hash = (37 * hash) + STATUS_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getStatusMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FavoriteAction.douyin_favorite_action_response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FavoriteAction.douyin_favorite_action_response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FavoriteAction.douyin_favorite_action_response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FavoriteAction.douyin_favorite_action_response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code douyin.extra.first.douyin_favorite_action_response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:douyin.extra.first.douyin_favorite_action_response)
        FavoriteAction.douyin_favorite_action_responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FavoriteAction.douyin_favorite_action_response.class, FavoriteAction.douyin_favorite_action_response.Builder.class);
      }

      // Construct using douyin.extra.first.FavoriteAction.douyin_favorite_action_response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statusCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        statusMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FavoriteAction.internal_static_douyin_extra_first_douyin_favorite_action_response_descriptor;
      }

      @java.lang.Override
      public FavoriteAction.douyin_favorite_action_response getDefaultInstanceForType() {
        return FavoriteAction.douyin_favorite_action_response.getDefaultInstance();
      }

      @java.lang.Override
      public FavoriteAction.douyin_favorite_action_response build() {
        FavoriteAction.douyin_favorite_action_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FavoriteAction.douyin_favorite_action_response buildPartial() {
        FavoriteAction.douyin_favorite_action_response result = new FavoriteAction.douyin_favorite_action_response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.statusCode_ = statusCode_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.statusMsg_ = statusMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FavoriteAction.douyin_favorite_action_response) {
          return mergeFrom((FavoriteAction.douyin_favorite_action_response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FavoriteAction.douyin_favorite_action_response other) {
        if (other == FavoriteAction.douyin_favorite_action_response.getDefaultInstance()) return this;
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasStatusMsg()) {
          bitField0_ |= 0x00000002;
          statusMsg_ = other.statusMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStatusCode()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FavoriteAction.douyin_favorite_action_response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FavoriteAction.douyin_favorite_action_response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int statusCode_ ;
      /**
       * <pre>
       *状态码，0-成功，其他-失败
       * </pre>
       *
       * <code>required int32 status_code = 1;</code>
       * @return Whether the statusCode field is set.
       */
      @java.lang.Override
      public boolean hasStatusCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *状态码，0-成功，其他-失败
       * </pre>
       *
       * <code>required int32 status_code = 1;</code>
       * @return The statusCode.
       */
      @java.lang.Override
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <pre>
       *状态码，0-成功，其他-失败
       * </pre>
       *
       * <code>required int32 status_code = 1;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        bitField0_ |= 0x00000001;
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *状态码，0-成功，其他-失败
       * </pre>
       *
       * <code>required int32 status_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object statusMsg_ = "";
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @return Whether the statusMsg field is set.
       */
      public boolean hasStatusMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @return The statusMsg.
       */
      public java.lang.String getStatusMsg() {
        java.lang.Object ref = statusMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            statusMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @return The bytes for statusMsg.
       */
      public com.google.protobuf.ByteString
          getStatusMsgBytes() {
        java.lang.Object ref = statusMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @param value The statusMsg to set.
       * @return This builder for chaining.
       */
      public Builder setStatusMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        statusMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        statusMsg_ = getDefaultInstance().getStatusMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @param value The bytes for statusMsg to set.
       * @return This builder for chaining.
       */
      public Builder setStatusMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        statusMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:douyin.extra.first.douyin_favorite_action_response)
    }

    // @@protoc_insertion_point(class_scope:douyin.extra.first.douyin_favorite_action_response)
    private static final FavoriteAction.douyin_favorite_action_response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FavoriteAction.douyin_favorite_action_response();
    }

    public static FavoriteAction.douyin_favorite_action_response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<douyin_favorite_action_response>
        PARSER = new com.google.protobuf.AbstractParser<douyin_favorite_action_response>() {
      @java.lang.Override
      public douyin_favorite_action_response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new douyin_favorite_action_response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<douyin_favorite_action_response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<douyin_favorite_action_response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FavoriteAction.douyin_favorite_action_response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_douyin_favorite_action_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_douyin_favorite_action_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_douyin_favorite_action_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_douyin_favorite_action_response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025favorite_action.proto\022\022douyin.extra.fi" +
      "rst\"f\n\036douyin_favorite_action_request\022\017\n" +
      "\007user_id\030\001 \002(\003\022\r\n\005token\030\002 \002(\t\022\020\n\010video_i" +
      "d\030\003 \002(\003\022\022\n\nactionType\030\004 \002(\005\"J\n\037douyin_fa" +
      "vorite_action_response\022\023\n\013status_code\030\001 " +
      "\002(\005\022\022\n\nstatus_msg\030\002 \001(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_douyin_extra_first_douyin_favorite_action_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_douyin_extra_first_douyin_favorite_action_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_douyin_favorite_action_request_descriptor,
        new java.lang.String[] { "UserId", "Token", "VideoId", "ActionType", });
    internal_static_douyin_extra_first_douyin_favorite_action_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_douyin_extra_first_douyin_favorite_action_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_douyin_favorite_action_response_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
