// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin/userMsg.proto

package com.example.kdoushen.douyin.bean.protobuf.user;

public final class UserMsg {
  private UserMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface douyin_user_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:douyin_user_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>required int64 user_id = 1;</code>
     * @return Whether the userId field is set.
     */
    boolean hasUserId();
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>required int64 user_id = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return Whether the token field is set.
     */
    boolean hasToken();
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return The token.
     */
    String getToken();
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code douyin_user_request}
   */
  public static final class douyin_user_request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:douyin_user_request)
      douyin_user_requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use douyin_user_request.newBuilder() to construct.
    private douyin_user_request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private douyin_user_request() {
      token_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new douyin_user_request();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private douyin_user_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              token_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserMsg.internal_static_douyin_user_request_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserMsg.internal_static_douyin_user_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserMsg.douyin_user_request.class, UserMsg.douyin_user_request.Builder.class);
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>required int64 user_id = 1;</code>
     * @return Whether the userId field is set.
     */
    @Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>required int64 user_id = 1;</code>
     * @return The userId.
     */
    @Override
    public long getUserId() {
      return userId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile Object token_;
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return Whether the token field is set.
     */
    @Override
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return The token.
     */
    @Override
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *用户鉴权token
     * </pre>
     *
     * <code>required string token = 2;</code>
     * @return The bytes for token.
     */
    @Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserMsg.douyin_user_request)) {
        return super.equals(obj);
      }
      UserMsg.douyin_user_request other = (UserMsg.douyin_user_request) obj;

      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (getUserId()
            != other.getUserId()) return false;
      }
      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserId()) {
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
      }
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserMsg.douyin_user_request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.douyin_user_request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.douyin_user_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.douyin_user_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.douyin_user_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.douyin_user_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.douyin_user_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserMsg.douyin_user_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserMsg.douyin_user_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserMsg.douyin_user_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserMsg.douyin_user_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserMsg.douyin_user_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserMsg.douyin_user_request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code douyin_user_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:douyin_user_request)
        UserMsg.douyin_user_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserMsg.internal_static_douyin_user_request_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserMsg.internal_static_douyin_user_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserMsg.douyin_user_request.class, UserMsg.douyin_user_request.Builder.class);
      }

      // Construct using com.example.kdoushen.douyin.core.UserMsg.douyin_user_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserMsg.internal_static_douyin_user_request_descriptor;
      }

      @Override
      public UserMsg.douyin_user_request getDefaultInstanceForType() {
        return UserMsg.douyin_user_request.getDefaultInstance();
      }

      @Override
      public UserMsg.douyin_user_request build() {
        UserMsg.douyin_user_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserMsg.douyin_user_request buildPartial() {
        UserMsg.douyin_user_request result = new UserMsg.douyin_user_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserMsg.douyin_user_request) {
          return mergeFrom((UserMsg.douyin_user_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserMsg.douyin_user_request other) {
        if (other == UserMsg.douyin_user_request.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000002;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasUserId()) {
          return false;
        }
        if (!hasToken()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserMsg.douyin_user_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserMsg.douyin_user_request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>required int64 user_id = 1;</code>
       * @return Whether the userId field is set.
       */
      @Override
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>required int64 user_id = 1;</code>
       * @return The userId.
       */
      @Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>required int64 user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>required int64 user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @return Whether the token field is set.
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @return The token.
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户鉴权token
       * </pre>
       *
       * <code>required string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:douyin_user_request)
    }

    // @@protoc_insertion_point(class_scope:douyin_user_request)
    private static final UserMsg.douyin_user_request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserMsg.douyin_user_request();
    }

    public static UserMsg.douyin_user_request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<douyin_user_request>
        PARSER = new com.google.protobuf.AbstractParser<douyin_user_request>() {
      @Override
      public douyin_user_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new douyin_user_request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<douyin_user_request> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<douyin_user_request> getParserForType() {
      return PARSER;
    }

    @Override
    public UserMsg.douyin_user_request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface douyin_user_responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:douyin_user_response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *状态码 0-成功，其他-失败
     * </pre>
     *
     * <code>required int32 status_code = 1;</code>
     * @return Whether the statusCode field is set.
     */
    boolean hasStatusCode();
    /**
     * <pre>
     *状态码 0-成功，其他-失败
     * </pre>
     *
     * <code>required int32 status_code = 1;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return Whether the statusMsg field is set.
     */
    boolean hasStatusMsg();
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return The statusMsg.
     */
    String getStatusMsg();
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return The bytes for statusMsg.
     */
    com.google.protobuf.ByteString
        getStatusMsgBytes();

    /**
     * <code>required .User user = 3;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>required .User user = 3;</code>
     * @return The user.
     */
    UserMsg.User getUser();
    /**
     * <code>required .User user = 3;</code>
     */
    UserMsg.UserOrBuilder getUserOrBuilder();
  }
  /**
   * Protobuf type {@code douyin_user_response}
   */
  public static final class douyin_user_response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:douyin_user_response)
      douyin_user_responseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use douyin_user_response.newBuilder() to construct.
    private douyin_user_response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private douyin_user_response() {
      statusMsg_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new douyin_user_response();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private douyin_user_response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              statusCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              statusMsg_ = bs;
              break;
            }
            case 26: {
              UserMsg.User.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(UserMsg.User.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserMsg.internal_static_douyin_user_response_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserMsg.internal_static_douyin_user_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserMsg.douyin_user_response.class, UserMsg.douyin_user_response.Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_CODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <pre>
     *状态码 0-成功，其他-失败
     * </pre>
     *
     * <code>required int32 status_code = 1;</code>
     * @return Whether the statusCode field is set.
     */
    @Override
    public boolean hasStatusCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *状态码 0-成功，其他-失败
     * </pre>
     *
     * <code>required int32 status_code = 1;</code>
     * @return The statusCode.
     */
    @Override
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int STATUS_MSG_FIELD_NUMBER = 2;
    private volatile Object statusMsg_;
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return Whether the statusMsg field is set.
     */
    @Override
    public boolean hasStatusMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return The statusMsg.
     */
    @Override
    public String getStatusMsg() {
      Object ref = statusMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          statusMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *返回状态描述
     * </pre>
     *
     * <code>optional string status_msg = 2;</code>
     * @return The bytes for statusMsg.
     */
    @Override
    public com.google.protobuf.ByteString
        getStatusMsgBytes() {
      Object ref = statusMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        statusMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 3;
    private UserMsg.User user_;
    /**
     * <code>required .User user = 3;</code>
     * @return Whether the user field is set.
     */
    @Override
    public boolean hasUser() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .User user = 3;</code>
     * @return The user.
     */
    @Override
    public UserMsg.User getUser() {
      return user_ == null ? UserMsg.User.getDefaultInstance() : user_;
    }
    /**
     * <code>required .User user = 3;</code>
     */
    @Override
    public UserMsg.UserOrBuilder getUserOrBuilder() {
      return user_ == null ? UserMsg.User.getDefaultInstance() : user_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatusCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUser().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, statusCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, statusMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getUser());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, statusCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, statusMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUser());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserMsg.douyin_user_response)) {
        return super.equals(obj);
      }
      UserMsg.douyin_user_response other = (UserMsg.douyin_user_response) obj;

      if (hasStatusCode() != other.hasStatusCode()) return false;
      if (hasStatusCode()) {
        if (getStatusCode()
            != other.getStatusCode()) return false;
      }
      if (hasStatusMsg() != other.hasStatusMsg()) return false;
      if (hasStatusMsg()) {
        if (!getStatusMsg()
            .equals(other.getStatusMsg())) return false;
      }
      if (hasUser() != other.hasUser()) return false;
      if (hasUser()) {
        if (!getUser()
            .equals(other.getUser())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatusCode()) {
        hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getStatusCode();
      }
      if (hasStatusMsg()) {
        hash = (37 * hash) + STATUS_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getStatusMsg().hashCode();
      }
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserMsg.douyin_user_response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.douyin_user_response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.douyin_user_response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.douyin_user_response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.douyin_user_response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.douyin_user_response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.douyin_user_response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserMsg.douyin_user_response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserMsg.douyin_user_response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserMsg.douyin_user_response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserMsg.douyin_user_response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserMsg.douyin_user_response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserMsg.douyin_user_response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code douyin_user_response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:douyin_user_response)
        UserMsg.douyin_user_responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserMsg.internal_static_douyin_user_response_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserMsg.internal_static_douyin_user_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserMsg.douyin_user_response.class, UserMsg.douyin_user_response.Builder.class);
      }

      // Construct using com.example.kdoushen.douyin.core.UserMsg.douyin_user_response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        statusCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        statusMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserMsg.internal_static_douyin_user_response_descriptor;
      }

      @Override
      public UserMsg.douyin_user_response getDefaultInstanceForType() {
        return UserMsg.douyin_user_response.getDefaultInstance();
      }

      @Override
      public UserMsg.douyin_user_response build() {
        UserMsg.douyin_user_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserMsg.douyin_user_response buildPartial() {
        UserMsg.douyin_user_response result = new UserMsg.douyin_user_response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.statusCode_ = statusCode_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.statusMsg_ = statusMsg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (userBuilder_ == null) {
            result.user_ = user_;
          } else {
            result.user_ = userBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserMsg.douyin_user_response) {
          return mergeFrom((UserMsg.douyin_user_response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserMsg.douyin_user_response other) {
        if (other == UserMsg.douyin_user_response.getDefaultInstance()) return this;
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasStatusMsg()) {
          bitField0_ |= 0x00000002;
          statusMsg_ = other.statusMsg_;
          onChanged();
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasStatusCode()) {
          return false;
        }
        if (!hasUser()) {
          return false;
        }
        if (!getUser().isInitialized()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserMsg.douyin_user_response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserMsg.douyin_user_response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int statusCode_ ;
      /**
       * <pre>
       *状态码 0-成功，其他-失败
       * </pre>
       *
       * <code>required int32 status_code = 1;</code>
       * @return Whether the statusCode field is set.
       */
      @Override
      public boolean hasStatusCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *状态码 0-成功，其他-失败
       * </pre>
       *
       * <code>required int32 status_code = 1;</code>
       * @return The statusCode.
       */
      @Override
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <pre>
       *状态码 0-成功，其他-失败
       * </pre>
       *
       * <code>required int32 status_code = 1;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        bitField0_ |= 0x00000001;
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *状态码 0-成功，其他-失败
       * </pre>
       *
       * <code>required int32 status_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private Object statusMsg_ = "";
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @return Whether the statusMsg field is set.
       */
      public boolean hasStatusMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @return The statusMsg.
       */
      public String getStatusMsg() {
        Object ref = statusMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            statusMsg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @return The bytes for statusMsg.
       */
      public com.google.protobuf.ByteString
          getStatusMsgBytes() {
        Object ref = statusMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          statusMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @param value The statusMsg to set.
       * @return This builder for chaining.
       */
      public Builder setStatusMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        statusMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        statusMsg_ = getDefaultInstance().getStatusMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回状态描述
       * </pre>
       *
       * <code>optional string status_msg = 2;</code>
       * @param value The bytes for statusMsg to set.
       * @return This builder for chaining.
       */
      public Builder setStatusMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        statusMsg_ = value;
        onChanged();
        return this;
      }

      private UserMsg.User user_;
      private com.google.protobuf.SingleFieldBuilderV3<
          User, User.Builder, UserOrBuilder> userBuilder_;
      /**
       * <code>required .User user = 3;</code>
       * @return Whether the user field is set.
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .User user = 3;</code>
       * @return The user.
       */
      public UserMsg.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? UserMsg.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>required .User user = 3;</code>
       */
      public Builder setUser(UserMsg.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .User user = 3;</code>
       */
      public Builder setUser(
          UserMsg.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .User user = 3;</code>
       */
      public Builder mergeUser(UserMsg.User value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              user_ != null &&
              user_ != UserMsg.User.getDefaultInstance()) {
            user_ =
              UserMsg.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .User user = 3;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .User user = 3;</code>
       */
      public UserMsg.User.Builder getUserBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>required .User user = 3;</code>
       */
      public UserMsg.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              UserMsg.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>required .User user = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          User, User.Builder, UserOrBuilder>
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              User, User.Builder, UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:douyin_user_response)
    }

    // @@protoc_insertion_point(class_scope:douyin_user_response)
    private static final UserMsg.douyin_user_response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserMsg.douyin_user_response();
    }

    public static UserMsg.douyin_user_response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<douyin_user_response>
        PARSER = new com.google.protobuf.AbstractParser<douyin_user_response>() {
      @Override
      public douyin_user_response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new douyin_user_response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<douyin_user_response> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<douyin_user_response> getParserForType() {
      return PARSER;
    }

    @Override
    public UserMsg.douyin_user_response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户唯一id
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <pre>
     *用户唯一id
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *关注总数
     * </pre>
     *
     * <code>optional int64 follow_count = 3;</code>
     * @return Whether the followCount field is set.
     */
    boolean hasFollowCount();
    /**
     * <pre>
     *关注总数
     * </pre>
     *
     * <code>optional int64 follow_count = 3;</code>
     * @return The followCount.
     */
    long getFollowCount();

    /**
     * <pre>
     *粉丝总数
     * </pre>
     *
     * <code>optional int64 follower_count = 4;</code>
     * @return Whether the followerCount field is set.
     */
    boolean hasFollowerCount();
    /**
     * <pre>
     *粉丝总数
     * </pre>
     *
     * <code>optional int64 follower_count = 4;</code>
     * @return The followerCount.
     */
    long getFollowerCount();

    /**
     * <pre>
     *true-已关注，false-未关注
     * </pre>
     *
     * <code>required bool is_follow = 5;</code>
     * @return Whether the isFollow field is set.
     */
    boolean hasIsFollow();
    /**
     * <pre>
     *true-已关注，false-未关注
     * </pre>
     *
     * <code>required bool is_follow = 5;</code>
     * @return The isFollow.
     */
    boolean getIsFollow();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              followCount_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              followerCount_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isFollow_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserMsg.internal_static_User_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserMsg.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserMsg.User.class, UserMsg.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *用户唯一id
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *用户唯一id
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    @Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FOLLOW_COUNT_FIELD_NUMBER = 3;
    private long followCount_;
    /**
     * <pre>
     *关注总数
     * </pre>
     *
     * <code>optional int64 follow_count = 3;</code>
     * @return Whether the followCount field is set.
     */
    @Override
    public boolean hasFollowCount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *关注总数
     * </pre>
     *
     * <code>optional int64 follow_count = 3;</code>
     * @return The followCount.
     */
    @Override
    public long getFollowCount() {
      return followCount_;
    }

    public static final int FOLLOWER_COUNT_FIELD_NUMBER = 4;
    private long followerCount_;
    /**
     * <pre>
     *粉丝总数
     * </pre>
     *
     * <code>optional int64 follower_count = 4;</code>
     * @return Whether the followerCount field is set.
     */
    @Override
    public boolean hasFollowerCount() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *粉丝总数
     * </pre>
     *
     * <code>optional int64 follower_count = 4;</code>
     * @return The followerCount.
     */
    @Override
    public long getFollowerCount() {
      return followerCount_;
    }

    public static final int IS_FOLLOW_FIELD_NUMBER = 5;
    private boolean isFollow_;
    /**
     * <pre>
     *true-已关注，false-未关注
     * </pre>
     *
     * <code>required bool is_follow = 5;</code>
     * @return Whether the isFollow field is set.
     */
    @Override
    public boolean hasIsFollow() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *true-已关注，false-未关注
     * </pre>
     *
     * <code>required bool is_follow = 5;</code>
     * @return The isFollow.
     */
    @Override
    public boolean getIsFollow() {
      return isFollow_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsFollow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, followCount_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, followerCount_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, isFollow_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, followCount_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, followerCount_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isFollow_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserMsg.User)) {
        return super.equals(obj);
      }
      UserMsg.User other = (UserMsg.User) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasFollowCount() != other.hasFollowCount()) return false;
      if (hasFollowCount()) {
        if (getFollowCount()
            != other.getFollowCount()) return false;
      }
      if (hasFollowerCount() != other.hasFollowerCount()) return false;
      if (hasFollowerCount()) {
        if (getFollowerCount()
            != other.getFollowerCount()) return false;
      }
      if (hasIsFollow() != other.hasIsFollow()) return false;
      if (hasIsFollow()) {
        if (getIsFollow()
            != other.getIsFollow()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasFollowCount()) {
        hash = (37 * hash) + FOLLOW_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFollowCount());
      }
      if (hasFollowerCount()) {
        hash = (37 * hash) + FOLLOWER_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFollowerCount());
      }
      if (hasIsFollow()) {
        hash = (37 * hash) + IS_FOLLOW_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsFollow());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserMsg.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMsg.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMsg.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserMsg.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserMsg.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserMsg.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserMsg.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserMsg.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserMsg.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        UserMsg.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserMsg.internal_static_User_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserMsg.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserMsg.User.class, UserMsg.User.Builder.class);
      }

      // Construct using com.example.kdoushen.douyin.core.UserMsg.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        followCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        followerCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        isFollow_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserMsg.internal_static_User_descriptor;
      }

      @Override
      public UserMsg.User getDefaultInstanceForType() {
        return UserMsg.User.getDefaultInstance();
      }

      @Override
      public UserMsg.User build() {
        UserMsg.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserMsg.User buildPartial() {
        UserMsg.User result = new UserMsg.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.followCount_ = followCount_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.followerCount_ = followerCount_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.isFollow_ = isFollow_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserMsg.User) {
          return mergeFrom((UserMsg.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserMsg.User other) {
        if (other == UserMsg.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasFollowCount()) {
          setFollowCount(other.getFollowCount());
        }
        if (other.hasFollowerCount()) {
          setFollowerCount(other.getFollowerCount());
        }
        if (other.hasIsFollow()) {
          setIsFollow(other.getIsFollow());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasIsFollow()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserMsg.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserMsg.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       *用户唯一id
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *用户唯一id
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *用户唯一id
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户唯一id
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private long followCount_ ;
      /**
       * <pre>
       *关注总数
       * </pre>
       *
       * <code>optional int64 follow_count = 3;</code>
       * @return Whether the followCount field is set.
       */
      @Override
      public boolean hasFollowCount() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *关注总数
       * </pre>
       *
       * <code>optional int64 follow_count = 3;</code>
       * @return The followCount.
       */
      @Override
      public long getFollowCount() {
        return followCount_;
      }
      /**
       * <pre>
       *关注总数
       * </pre>
       *
       * <code>optional int64 follow_count = 3;</code>
       * @param value The followCount to set.
       * @return This builder for chaining.
       */
      public Builder setFollowCount(long value) {
        bitField0_ |= 0x00000004;
        followCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *关注总数
       * </pre>
       *
       * <code>optional int64 follow_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFollowCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        followCount_ = 0L;
        onChanged();
        return this;
      }

      private long followerCount_ ;
      /**
       * <pre>
       *粉丝总数
       * </pre>
       *
       * <code>optional int64 follower_count = 4;</code>
       * @return Whether the followerCount field is set.
       */
      @Override
      public boolean hasFollowerCount() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *粉丝总数
       * </pre>
       *
       * <code>optional int64 follower_count = 4;</code>
       * @return The followerCount.
       */
      @Override
      public long getFollowerCount() {
        return followerCount_;
      }
      /**
       * <pre>
       *粉丝总数
       * </pre>
       *
       * <code>optional int64 follower_count = 4;</code>
       * @param value The followerCount to set.
       * @return This builder for chaining.
       */
      public Builder setFollowerCount(long value) {
        bitField0_ |= 0x00000008;
        followerCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *粉丝总数
       * </pre>
       *
       * <code>optional int64 follower_count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFollowerCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        followerCount_ = 0L;
        onChanged();
        return this;
      }

      private boolean isFollow_ ;
      /**
       * <pre>
       *true-已关注，false-未关注
       * </pre>
       *
       * <code>required bool is_follow = 5;</code>
       * @return Whether the isFollow field is set.
       */
      @Override
      public boolean hasIsFollow() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *true-已关注，false-未关注
       * </pre>
       *
       * <code>required bool is_follow = 5;</code>
       * @return The isFollow.
       */
      @Override
      public boolean getIsFollow() {
        return isFollow_;
      }
      /**
       * <pre>
       *true-已关注，false-未关注
       * </pre>
       *
       * <code>required bool is_follow = 5;</code>
       * @param value The isFollow to set.
       * @return This builder for chaining.
       */
      public Builder setIsFollow(boolean value) {
        bitField0_ |= 0x00000010;
        isFollow_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *true-已关注，false-未关注
       * </pre>
       *
       * <code>required bool is_follow = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFollow() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isFollow_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final UserMsg.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserMsg.User();
    }

    public static UserMsg.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @Override
    public UserMsg.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_user_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_user_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_user_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_user_response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024douyin/userMsg.proto\"5\n\023douyin_user_re" +
      "quest\022\017\n\007user_id\030\001 \002(\003\022\r\n\005token\030\002 \002(\t\"T\n" +
      "\024douyin_user_response\022\023\n\013status_code\030\001 \002" +
      "(\005\022\022\n\nstatus_msg\030\002 \001(\t\022\023\n\004user\030\003 \002(\0132\005.U" +
      "ser\"a\n\004User\022\n\n\002id\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022\024\n" +
      "\014follow_count\030\003 \001(\003\022\026\n\016follower_count\030\004 " +
      "\001(\003\022\021\n\tis_follow\030\005 \002(\010B\"\n com.example.kd" +
      "oushen.douyin.core"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_douyin_user_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_douyin_user_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_user_request_descriptor,
        new String[] { "UserId", "Token", });
    internal_static_douyin_user_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_douyin_user_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_user_response_descriptor,
        new String[] { "StatusCode", "StatusMsg", "User", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new String[] { "Id", "Name", "FollowCount", "FollowerCount", "IsFollow", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
